// Re-export from MoonBit build output (api_js)
// This file exists to apply TypeScript types from index.d.ts
export {
  // Signal API
  createSignal,
  get,
  set,
  update,
  peek,
  subscribe,
  map,
  createMemo,
  combine,
  effect,
  batchStart,
  batchEnd,
  runUntracked,
  batch,
  onCleanup,
  createRoot,
  getOwner,
  runWithOwner,
  hasOwner,
  onMount,
  // DOM API
  text,
  textDyn,
  render,
  mount,
  show,
  jsx,
  jsxs,
  Fragment,
  createElement,
  events,
  forEach,
  // Timer utilities
  debounced,
  // Route definitions
  routePage,
  routePageTitled,
  routePageFull,
  routeGroup,
  routeParam,
  createRouter,
  routerNavigate,
  routerReplace,
  routerGetPath,
  routerGetMatch,
  routerGetBase,
} from "../../target/js/release/build/lib/api_js/api_js.js";
